name: Dev Run Tests

on:
  push:
    branches:
      - dev

permissions:
  pull-requests: write
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4

      - name: Testing in NodeJS ${{ matrix.node-version }} ${{secrets.message}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
